version: "3"

networks:
  minha-rede:
    driver: bridge

services:
  express-app:
    build: .
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - minha-rede
    links:
      - mysqldb
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=todolist
    volumes:
      - .:/app/

  mysqldb:
    image: mysql:5.7
    networks:
      - minha-rede
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todolist
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
